# Generated by Django 5.2.8 on 2025-11-17 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='common', max_length=100)),
                ('name', models.CharField(default='Name', max_length=300)),
                ('text', models.TextField(default='Lorem')),
                ('avatar_name', models.CharField(default='default', max_length=255)),
            ],
        ),
    ]
