# Generated by Django 5.2.8 on 2025-11-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_site_app', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_moderate_reviews', 'Может модерировать отзывы'), ('can_delete_reviews', 'Может удалять отзывы')]},
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(null=True, to='films_site_app.genre'),
        ),
    ]
