# Generated by Django 5.2.8 on 2025-11-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_site_app', '0004_genre_alter_review_options_film_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'permissions': [('can_moderate_genre', 'Может модерировать жанр'), ('can_delete_genre', 'Может удалять жанр'), ('can_add_genre', 'Может добавлять жанр')]},
        ),
    ]
